### ISSUE TITLE
config.js の内容が index.html に反映されない

### ISSUE THREAD

**Issue by shioue22** [furuhashilab/ishikawa100mangoku2023gpsart_b#10]
**[index.html](https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/blob/main/index.html)の表示（オフライン）**
![config](https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/assets/106800258/493c3fc0-cd9e-41f9-8648-62617b117ca6)

**[config.js](gpsart_b/blob/main/config.js.)**
![page](https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/assets/106800258/386c80ac-8269-4586-8349-9a7675d1b6f9)

**エラーコード**
![エラーコード](https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/assets/106800258/3ddf37f3-5b0a-4232-8eeb-8ce7c88f254c)

更新したコードがPreveiwできないため、成果物として発表できるページがありません。申し訳ございません。

**Comment by shioue22** [comment]
**エラーコード２**
![スクリーンショット (127)](https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/assets/106800258/af484541-a4c6-4114-9f9d-37809eb7ba3e)

**Comment by shioue22** [comment]
オフライン環境で表示されない問題は、アクセストークンキーを更新前に戻すことで解決。

しかし、アクセストークンだけを変えたのに更新したはずのGPXデータが地図上に表示されなくなりました。
![スクリーンショット (128)](https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/assets/106800258/2e98e3bc-e771-4ee7-af07-a95ac95ca724)

**Comment by mapconcierge** [comment]
* [x] ファイル名の拡張子が問題があったので修正しました。
https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/commit/082b63ed6cf55998f6bb9f95f516cec77992362a

* [x] Mapbox GL JS のアクセストークンと Style 設定のURLを古橋個人アカウントで修正して動作確認
https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/commit/cea873104b35993c68c236df4fdbddb680398752

<img width="2240" alt="スクリーンショット 2023-10-10 11 57 25" src="https://github.com/furuhashilab/ishikawa100mangoku2023gpsart_b/assets/416977/7a02d09a-0d36-4378-ae0d-d15bf12dc24c">

これでウェブ上で正しく地図も表示されることが確認できた。
